# Generated by Django 3.2.3 on 2021-05-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='hostName',
        ),
    ]
