# Generated by Django 3.2.3 on 2021-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_auto_20210629_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('Architecture', 'ARCHITECTURE'), ('Art', 'ART'), ('Business', 'BUSINESS'), ('Content Writing', 'CONTENT WRITING'), ('Cooking', 'COOKING'), ('Dance', 'DANCE'), ('Gardening', 'GARDENING'), ('Photography', 'PHOTOGRAPHY'), ('Technology', 'TECHNOLOGY')], default='Architecture', max_length=20),
        ),
    ]
