# Generated by Django 3.2.3 on 2021-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
